### PR TITLE
Bug 1531871 - [major] upgrade dependencies

### PR DESCRIPTION
**Pull request by djmitche**
The last commit is a somewhat-incompatible change.  It is forward-compatible, but not backward-compatible.  It is only backward-incompatible when a new schema is introduced by a new version of this library and consumed by an old version.

### CODE REVIEW

**Comment by djmitche** [comment]
I can't seem to flag services-reviewers for review on this.. I don't know why.

**Comment by djmitche** [comment]
remind me to install renovate when this is landed.

**Comment by imbstack** [comment]
The tests are failing for an unrelated reason I think? Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1532387 for the `Buffer` stuff. I'll review this later today.

**Comment by djmitche** [comment]
Yes, test failures are because I made a PR from a branch in my repo..

**Pull request merged**
